name = "Universal Scene Description"
grammar = "usd"
path_suffixes = ["usda"]
line_comments = ["#"]
block_comment = ["/*", "*/"]
autoclose_before = "}])"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
]
